from enum import Enum

class GitLineCategory(str, Enum):
    UNKNOWN = "UNKNOWN"
    EMPTY = "EMPTY"
    SYMBOLS_ONLY = "SYMBOLS_ONLY"
    CODE = "CODE"
    COMMENT = "COMMENT"

class GitCommitStatisticCategory(str, Enum):
    INSERTIONS = "INSERTIONS"
    DELETIONS = "DELETIONS"
    MODIFICATIONS = "MODIFICATIONS"

class GitRepositoryStatisticCategory(str, Enum):
    SURVIVED_LINES = "SURVIVED_LINES"
    INSERTIONS = "INSERTIONS"
    DELETIONS = "DELETIONS"
    MODIFICATIONS = "MODIFICATIONS"
    COMMITS = "COMMITS"
    MERGE_INSERTIONS = "MERGE_INSERTIONS"
    MERGE_DELETIONS = "MERGE_DELETIONS"
    MERGE_MODIFICATIONS = "MERGE_MODIFICATIONS"
    MERGE_COMMITS = "MERGE_COMMITS"
